### ISSUE TITLE
Integration error US16

### ISSUE THREAD

**Issue by 55Brian55** [jj1976/SSW555AgileMethodsCJBS#85]
Chris,

I keep getting a key error "jc" when I initiate checks yet code tests fine. Any clues why? I actually think it tested OK yesterday at some point. 
======================================================================
ERROR: test_parser (testSprint2.Sprint2OutputTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jj1976/SSW555AgileMethodsCJBS/tests/testSprint2.py", line 19, in test_parser
    validate_families(sprint2_data[0], sprint2_data[1])
  File "/home/travis/build/jj1976/SSW555AgileMethodsCJBS/GedcomParser.py", line 223, in validate_families
    family.validate_male_last(individual_data)
  File "/home/travis/build/jj1976/SSW555AgileMethodsCJBS/models/Family.py", line 296, in validate_male_last
    husband=individuals[self.husband_id]
KeyError: 'jc'
======================================================================
ERROR: test_parser (testSprint3.Sprint3OutputTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/jj1976/SSW555AgileMethodsCJBS/tests/testSprint3.py", line 19, in test_parser
    validate_families(sprint3_data[0], sprint3_data[1])
  File "/home/travis/build/jj1976/SSW555AgileMethodsCJBS/GedcomParser.py", line 223, in validate_families
    family.validate_male_last(individual_data)
  File "/home/travis/build/jj1976/SSW555AgileMethodsCJBS/models/Family.py", line 296, in validate_male_last
    husband=individuals[self.husband_id]
KeyError: 'jc'
----------------------------------------------------------------------
Ran 63 tests in 0.437s
FAILED (errors=2)

**Comment by 55Brian55** [comment]
Chris,
Disregard. I add check for a valid I substring check prior execution and it worked. There must be some Individual IDs which are not @I1@ format that are husbands ( other than blanks of course).
